version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD
      - DB_NAME=nodebank
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  frontend:
    build: ./bank-front
    ports:
      - '3001:80'
    environment:
      - NODE_ENV=development
    volumes:
      - ./bank-front:/usr/src/app

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: nodebank
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD:
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mariadb_data:
